Use https instead of unauthenticated git protocol.
Sample error:

```
Fetching upstream changes from git://github.com/plone/buildout.coredev.git
 > git --version # timeout=10
 > git --version # 'git version 2.17.1'
 > git fetch --no-tags --progress --depth=10 -- git://github.com/plone/buildout.coredev.git +refs/heads/*:refs/remotes/origin/* # timeout=10
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "git fetch --no-tags --progress --depth=10 -- git://github.com/plone/buildout.coredev.git +refs/heads/*:refs/remotes/origin/*" returned status code 128:
stdout:
stderr: fatal: remote error:
  The unauthenticated git protocol on port 9418 is no longer supported.
```

See for example this PR job:
https://jenkins.plone.org/job/pull-request-6.0-3.7/1029/console